baseURL = 'https://weissengrubernina.github.io/hugoSite/'
languageCode = 'en-us'
title = 'Leonie'
theme = "leoTheme"

[menu]
  [[menu.main]]
    name = "Leonie"
    pre = "leonie"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Team"
    pre = "list"
    url = "https://weissengrubernina.github.io/hugoSite/team/"
    weight = 2
  [[menu.main]]
    name = "News"
    pre = "tag"
    url = "https://weissengrubernina.github.io/hugoSite/news/"
    weight = 3
