baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Leonie'
theme = "leoTheme"

[menu]
  [[menu.main]]
    name = "Leonie"
    pre = "leonie"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Team"
    pre = "list"
    url = "/team/"
    weight = 2
  [[menu.main]]
    name = "News"
    pre = "tag"
    url = "/news/"
    weight = 3