baseURL = 'https://weissengrubernina.github.io/hugoSite/'
languageCode = 'en-us'
title = 'Leonie'
theme = "leoTheme"

[menu]
  [[menu.main]]
    name = "Leonie"
    pre = "leonie"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 2
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 3
